name: bld-ci

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build-bld-project:
    env:
      COVERAGE_JDK: "17"

    strategy:
      matrix:
        java-version: [ 17, 21, 25 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java-version }}

      - name: Download dependencies
        run: ./bld download

      - name: Compile source
        run: ./bld compile

      - name: Run tests
        continue-on-error: true
        run: ./bld jacoco

      - name: Run reporter on failure
        if: ${{ failure() }}
        run: ./bld reporter --all

      - name: Remove pom.xml
        if: success() && matrix.java-version == env.COVERAGE_JDK && matrix.os == 'ubuntu-latest'
        run: rm -rf pom.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.3.1
        if: success() && matrix.java-version == env.COVERAGE_JDK && matrix.os == 'ubuntu-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
